<?
    //***********************************
    // For WEB_CORONA VER 3.0 php
    // Copyright: 2003. 6. 22 Dr.choi 
    //          : 2007. 7. 10 Dr.choi 
    //             Korea Linux Mannia
    //***********************************

    $CHARSET="euc-kr";

    if (!headers_sent()) {
      header("Content-Type:text/html; charset=$CHARSET");
      //header('Expires: Mon, 26 Jul 1997 05:00:00 GMT');
      //header('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT');
      header('Cache-Control: private, no-cache');
      header('Pragma: no-cache');
    }

?>
